name: Build and Release

on: 
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-nuitka:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-nuitka:${{ env.short_sha }}
          platforms: linux/amd64,linux/arm64

  extract-and-upload:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Extract and compress /app directory for amd64
        run: |
          docker create --platform linux/amd64 --name extract_amd64 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-nuitka:latest
          docker cp extract_amd64:/app ./fastapi-nutika-${{ env.short_sha }}-amd64
          tar -czvf fastapi-nutika-${{ env.short_sha }}-amd64.tar.gz -C ./fastapi-nutika-${{ env.short_sha }}-amd64 .
          docker rm -f extract_amd64

      - name: Extract and compress /app directory for arm64
        run: |
          docker create --platform linux/arm64 --name extract_arm64 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-nuitka:latest
          docker cp extract_arm64:/app ./fastapi-nutika-${{ env.short_sha }}-arm64
          tar -czvf fastapi-nutika-${{ env.short_sha }}-arm64.tar.gz -C ./fastapi-nutika-${{ env.short_sha }}-arm64 .
          docker rm -f extract_arm64


      - name: Upload tar to release assets
        uses: ncipollo/release-action@v1
        with:
          tag: fastapi-nuitka-${{ env.short_sha }}
          allowUpdates: true
          artifacts: "fastapi-nutika-${{ env.short_sha }}-amd64.tar.gz,fastapi-nutika-${{ env.short_sha }}-arm64.tar.gz"

